### ISSUE TITLE
Extremely dense models (>70k verts) are not rendering correctly

### ISSUE THREAD

**Issue by NorthWindH** [cjcliffe/CubicVR#13]
Rendering very dense models is not happening correctly. We believe that the issue may be that WebGL restricts IBO elements to be shorts so indexing a vertex with an index over 65536 overflows and references an incorrect vertex. A possible solution may be to internally split the model up into multiple buffers?

**Comment by cjcliffe** [comment]
Whoops, wrong CubicVR (this is issue tracker for C++)..

There's a ticket related to this already in the CubicVR.js issue list:

https://github.com/cjcliffe/CubicVR.js/issues/70

I'll close this one for now :)
